### PR TITLE
Updating SWC introduction slides (now in 8 and with spiffy new PDF)

### PR DESCRIPTION
**Pull request by uiuc-cse**
I've updated the slides a bit in preparation for a presentation I'm doing in a couple of weeks.  The text is very similar to the older 4-slide introduction.  The font I've used is [Linux Biolinium](http://linuxlibertine.org/).  I've also included a PDF copy of the slides for those who don't have access to powerpoint.

### CODE REVIEW

**Comment by gvwilson** [comment]
Since January 2012, we've taught over 340 workshops...
...in over 25 countries

**Comment by gvwilson** [comment]
Take "data management (SQL)" out of the topic list (we no longer require it)

**Comment by gvwilson** [comment]
Probably best to take unit testing out of the curriculum as well - we don't usually teach it (and it isn't yet required again)

**Comment by uiuc-cse** [comment]
All of those changes have been made.  Although arguably "data management" (without the SQL qualifier) could remain.

**Pull request merged**
