### PR TITLE
SWC hex logo for stickers

### PR DESCRIPTION
**Pull request by noamross**
I made this for a [personal project](https://twitter.com/Voovarb/status/679859794719592449), and thought it might be useful in case SWC wants hex stickers.

### CODE REVIEW

**Comment by tpoisot** [comment]
Awesome!

Are they on stickermule? I would buy some data/software carpentry ones for the
lab.

Also, can you put then on hexb.in?

t


Sent from a mobile device. Pardon the typos/brevity.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.90&pv=5.1.1&source=email_footer_2] On jeu., déc. 24, 2015 at 8:52 AM, Noam Ross < notifications@github.com [notifications@github.com] > wrote:
I made this for a personal project [https://twitter.com/Voovarb/status/679859794719592449] , and thought it might be useful in case SWC wants hex stickers.


--------------------------------------------------------------------------------

YOU CAN VIEW, COMMENT ON, OR MERGE THIS PULL REQUEST ONLINE AT:
https://github.com/swcarpentry/communications/pull/42
[https://github.com/swcarpentry/communications/pull/42]

COMMIT SUMMARY
 * SWC hex logo for stickers

FILE CHANGES
 * A misc/logo/swc-hex-logo.svg
   [https://github.com/swcarpentry/communications/pull/42/files#diff-0] (1006)

PATCH LINKS:
 * https://github.com/swcarpentry/communications/pull/42.patch
   [https://github.com/swcarpentry/communications/pull/42.patch]
 * https://github.com/swcarpentry/communications/pull/42.diff
   [https://github.com/swcarpentry/communications/pull/42.diff]

**Comment by gvwilson** [comment]
You can buy Software Carpentry laptop stickers at 
https://www.stickermule.com/user/1070632011/stickers

**Comment by noamross** [comment]
@tpoisot I'll put this (and the data carpentry one) on hexb.in if it's accepted via proper parliamentary committee procedure. (That is, merged)

**Comment by gvwilson** [comment]
The SWC logo looks grainy, but more importantly, it has to have the 
hammer (that's what's trademarked).  Did you start with the SVG 
(attached)?  And can you please re-do with the hammer?

**Comment by noamross** [comment]
Updated version now uses the hammer, and fixes the previous pixelation issue.

**Comment by gvwilson** [comment]
You're going to hate me, but can you shrink the hammer so that it's 
actually hitting the nail?  Because right now I feel sorry for the 's' :-)

**Comment by noamross** [comment]
Took a crack at it.  What do people think?  I'm not sure this is the best solution to dealing with the problem of the SWC logo being inherently wide, while the hex is actually slightly taller than wide.

**Comment by gvwilson** [comment]
Ship it!

**Comment by jduckles** [comment]
Sorry for the delay in merging. Thanks @noamross!

**Pull request merged**
