### PR TITLE
A first stab at collecting grant prose

### PR DESCRIPTION
**Pull request by jduckles**
I tried to pull together what @gvwilson talked about in https://github.com/swcarpentry/communications/issues/11 and made a first cut at a generic voice throughout.  I tried to point to other pages and resources that might change where possible so as not to load down and obsolete this document.

### CODE REVIEW

**Comment by jduckles** [comment]
With the number I went with a count of the number of Members, I think there may be more badged, but they don't become members until they teach, so we should decide which number we want to put in there. Standby for your suggestions incorporated and a reflow of the paragraphs to multi-line.

**Comment by jduckles** [comment]
@iglpdc Thanks for giving it a read and your comments, I like them all and have incorporated them.

**Comment by jduckles** [comment]
@JasonJWilliamsNY Just looping you into this as it is related to Partners & Development sub-committee.

**Comment by adina** [comment]
Thanks @jduckles !

**Pull request merged**
