### PR TITLE
new flyer template

### PR DESCRIPTION
**Pull request by ScienceScribe**
I created a new flyer template that includes most of the text of the original flyer in the repo.

### CODE REVIEW

**Comment by iglpdc** [comment]
Thanks @ScienceScribe!

A couple of things, though:

- could you make the links to the web, email, and twitter clickable?
- the email should be admin@software-carpentry.org, not info@software-carpentry.org.
- our workshops for novices (most of what we teach) require no previous computing experience.

**Comment by kynan** [comment]
What's the policy on including generated material i.e. the PDF generated from the odt?

**Comment by iglpdc** [comment]
Sure, @kynan. I'd rather have no generated materials in the repo.

@ScienceScribe, could you please remove the pdf from your PR, as we can generate it from the odt file?

**Comment by kynan** [comment]
Also @ScienceScribe please do it by amending your commit (otherwise we end up having the binary blob in the repo anyway).

**Comment by ScienceScribe** [comment]
@iglpdc @kynan I made the links clickable, corrected the flyer text, deleted the PDF, and amended the commit. Also, fixed a few minor typos in the README.md

**Comment by kynan** [comment]
:+1:

**Comment by iglpdc** [comment]
Thanks!

**Pull request merged**
