### PR TITLE
New folder structure

### LINKED ISSUE #5: Create folders and organize create materials.
To do.

### PR DESCRIPTION
**Pull request by iglpdc**
Implementing the folder structure described in the main README file. Fixes #5.

### CODE REVIEW

**Comment by kynan** [comment]
Looks good to me!

**Comment by iglpdc** [comment]
@adina could you review this, please? I want to merge this (after review and corrections) before we have a lot of stuff in the repo.

**Comment by adina** [comment]
@iglpdc looks good, thank you for your help!

**Comment by iglpdc** [comment]
I'm merging it then.

**Pull request merged**
